#!/bin/bash
#
# drift-firstboot — apply operator config from the boot partition, once.
#
# Reads /boot/firmware/drift-node.conf (a plain KEY=value file the operator
# edits on any computer after flashing), translates it into the node's runtime
# environment, optionally brings up Wi-Fi, then disables itself so it never
# runs again. Missing or empty config is fine — the node boots on defaults.

set -u
LOG=/var/log/drift-firstboot.log
exec >>"${LOG}" 2>&1
echo "=== drift-firstboot $(date -u '+%Y-%m-%dT%H:%M:%SZ') ==="

# Bookworm mounts the boot partition at /boot/firmware; older layouts use /boot.
BOOT=/boot/firmware
[ -d "${BOOT}" ] || BOOT=/boot
CONF="${BOOT}/drift-node.conf"

if [ -f "${CONF}" ]; then
	echo "reading ${CONF}"
	set -a
	# shellcheck disable=SC1090
	. "${CONF}"
	set +a

	# 1. Runtime environment consumed by drift-node.service.
	{
		echo "# generated by drift-firstboot from ${CONF}"
		[ -n "${DRIFT_PEERS:-}" ]     && echo "DRIFT_PEERS=${DRIFT_PEERS}"
		[ -n "${DRIFT_NODE_PORT:-}" ] && echo "DRIFT_NODE_PORT=${DRIFT_NODE_PORT}"
	} > /etc/drift-node.env
	chmod 644 /etc/drift-node.env
	echo "wrote /etc/drift-node.env"

	# 2. Optional Wi-Fi (NetworkManager on Bookworm). Skip if no SSID given or
	#    the operator configured the network another way (Ethernet, Imager).
	if [ -n "${WIFI_SSID:-}" ] && command -v nmcli >/dev/null 2>&1; then
		echo "configuring Wi-Fi for SSID '${WIFI_SSID}'"
		if ! nmcli -t -f NAME connection show | grep -qx "drift-wifi"; then
			nmcli connection add type wifi con-name drift-wifi \
				ifname '*' ssid "${WIFI_SSID}"
		fi
		nmcli connection modify drift-wifi \
			wifi-sec.key-mgmt wpa-psk \
			wifi-sec.psk "${WIFI_PSK:-}" \
			connection.autoconnect yes
		nmcli connection up drift-wifi || echo "wifi up deferred (radio not ready yet)"
	fi
else
	echo "no ${CONF} — using defaults"
fi

# Run exactly once.
systemctl disable drift-firstboot.service
echo "drift-firstboot complete"
